adds getAllChunksInRegion function
PrismarineJS/prismarine-provider-anvil pull request #45
Opened 2021-07-05 14:51 UTC by u9g

2021-07-06 11:03 UTC, rom1504 commented on src/anvil.js
> +            chunks.push(await this.load(x * 32 + _x, z * 32 + _z))
does it work in parallel ? promise map

2021-07-07 01:21 UTC, u9g commented on src/anvil.js
> +            chunks.push(await this.load(x * 32 + _x, z * 32 + _z))
done

2021-07-07 15:34 UTC, rom1504 requested changes
can you update the doc with the new function

2021-07-07 15:36 UTC, u9g commented
> can you update the doc with the new function

done!

2021-07-07 16:25 UTC, rom1504 approved these changes

2021-07-07 16:26 UTC, merged

2021-07-07 16:26 UTC, rom1504 commented
might want to add a getAllRegions functions and an example on how to get all chunks of all regions ?

2021-07-07 16:45 UTC, u9g commented
> might want to add a getAllRegions functions and an example on how to get all chunks of all regions ?

regions are just the x z in the fileNames of the files made by the world generator, its just a matter of matching the file names with regex, to get the xz for the all regions, but I can add that too